apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      port: 80              # External port exposed by LoadBalancer
      targetPort: 8084      # Internal port your Spring Boot app listens on
